FROM inodb/python-selenium
# 2018 01 10
MAINTAINER <ranmufei@qq.com>

RUN apt-get update -y

RUN apt-get install curl wget bzip2 libfreetype6 libfontconfig1 -y 



RUN pip install \
    bs4

RUN  mkdir /tmp/phantomjs \
  && curl -L https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 \
        | tar -xj --strip-components=1 -C /tmp/phantomjs \
  && mv /tmp/phantomjs/bin/phantomjs /usr/local/bin 

COPY python "/python"




WORKDIR /python

ENTRYPOINT python './flashSale.py';'sh'


